import SwiftUI
import shared  // KMP shared framework

/// Main iOS content view.
///
/// Uses the Compose Multiplatform shared UI via the KMP iOS framework.
/// The shared module provides all screens; this is just the entry point.
struct ContentView: View {
    var body: some View {
        // The Compose Multiplatform iOS integration renders the shared
        // Compose UI inside a UIKit UIViewController, wrapped here in
        // a SwiftUI UIViewControllerRepresentable.
        ComposeView()
            .ignoresSafeArea(.all)
    }
}

/// Wraps the KMP Compose UI in a SwiftUI-compatible view.
struct ComposeView: UIViewControllerRepresentable {
    func makeUIViewController(context: Context) -> UIViewController {
        // MainKt.MainViewController() is generated by Compose Multiplatform
        // when you define a @Composable fun MainViewController() in iosMain.
        // For now, return a placeholder until the KMP build is configured.
        let vc = UIViewController()
        vc.view.backgroundColor = .systemBackground

        let label = UILabel()
        label.text = "Briolette Wallet\n\nCompose Multiplatform UI\nloading from shared module..."
        label.numberOfLines = 0
        label.textAlignment = .center
        label.translatesAutoresizingMaskIntoConstraints = false
        vc.view.addSubview(label)

        NSLayoutConstraint.activate([
            label.centerXAnchor.constraint(equalTo: vc.view.centerXAnchor),
            label.centerYAnchor.constraint(equalTo: vc.view.centerYAnchor),
            label.leadingAnchor.constraint(greaterThanOrEqualTo: vc.view.leadingAnchor, constant: 20),
        ])

        return vc
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}

#Preview {
    ContentView()
}
