package com.briolette.wallet

import android.content.Context
import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import com.briolette.wallet.data.WalletPersistence
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Android wallet persistence using AES-256-GCM with a hardware-backed
 * Android Keystore key.
 *
 * The wallet JSON is encrypted before being stored in SharedPreferences.
 * The AES key is generated inside the TEE (or StrongBox on supported
 * devices), so extracting the plaintext requires compromising the
 * hardware security module — not just rooting the device.
 *
 * Storage format in SharedPreferences: Base64(IV || ciphertext || tag)
 * where IV is 12 bytes and tag is 128 bits (appended by GCM).
 */
class AndroidWalletPersistence(context: Context) : WalletPersistence {
    private val prefs = context.getSharedPreferences("briolette_wallet", Context.MODE_PRIVATE)

    override suspend fun save(json: String) {
        val key = getOrCreateKey()
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv  // 12 bytes, generated by the provider
        val ciphertext = cipher.doFinal(json.toByteArray(Charsets.UTF_8))
        // Pack as IV + ciphertext (GCM tag is appended to ciphertext by default)
        val blob = ByteArray(iv.size + ciphertext.size)
        System.arraycopy(iv, 0, blob, 0, iv.size)
        System.arraycopy(ciphertext, 0, blob, iv.size, ciphertext.size)
        prefs.edit().putString(KEY_WALLET_JSON, Base64.encodeToString(blob, Base64.NO_WRAP)).apply()
    }

    override suspend fun load(): String? {
        val encoded = prefs.getString(KEY_WALLET_JSON, null) ?: return null
        return try {
            val blob = Base64.decode(encoded, Base64.NO_WRAP)
            if (blob.size < GCM_IV_LENGTH) return null
            val iv = blob.copyOfRange(0, GCM_IV_LENGTH)
            val ciphertext = blob.copyOfRange(GCM_IV_LENGTH, blob.size)
            val key = getOrCreateKey()
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv))
            String(cipher.doFinal(ciphertext), Charsets.UTF_8)
        } catch (e: Exception) {
            // Decryption failure (key wiped, tampered data, etc.)
            null
        }
    }

    override suspend fun clear() {
        prefs.edit().remove(KEY_WALLET_JSON).apply()
        // Also delete the Keystore key so a fresh one is generated next time.
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER)
        ks.load(null)
        if (ks.containsAlias(KEY_ALIAS)) {
            ks.deleteEntry(KEY_ALIAS)
        }
    }

    /**
     * Get the existing AES-256-GCM key from Android Keystore, or generate
     * a new one inside the TEE/StrongBox.
     */
    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER)
        ks.load(null)
        if (ks.containsAlias(KEY_ALIAS)) {
            return (ks.getEntry(KEY_ALIAS, null) as KeyStore.SecretKeyEntry).secretKey
        }
        val spec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setKeySize(256)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .apply {
                // Prefer StrongBox (dedicated SE) on API 28+; falls back to TEE.
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                    try {
                        setIsStrongBoxBacked(true)
                    } catch (_: Exception) {
                        // StrongBox not available; TEE is fine.
                    }
                }
            }
            .build()
        val keygen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
        keygen.init(spec)
        return keygen.generateKey()
    }

    companion object {
        private const val KEY_WALLET_JSON = "wallet_state_json"
        private const val KEY_ALIAS = "briolette_storage_key"
        private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_IV_LENGTH = 12
        private const val GCM_TAG_LENGTH_BITS = 128
    }
}
